apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
  labels:
    component: ubuntu-test
spec:
  nodeName: ubuntu-test
  containers:
    - name: ubuntu-test
      image: ghcr.io/phamxuanduong/test:latest
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: ubuntu-test
