apiVersion: v1
kind: Pod
metadata:
  name: httpd-master
  labels:
    component: web-master
spec:
  nodeName: daica-master
  containers:
    - name: httpd-master
      image: httpd
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-master
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: web-master
