name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: docker login ghcr.io -u phamxuanduong -p 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
