name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: docker login dhcr.io -u phamxuanduong -p dckr_pat_PPcU4MALZdf1u2Q40jEFcsARD9o
