name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.1'
        id: install
      -
        run: kubectl config use-context microk8s
      -
        run: kubectl version
      -
        run: kubectl get pod
