name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - run: cat /home/runner/.kube/config
      - run: export KUBECONFIG=${HOME}/.kube/config
      - run: pwd
      - run: kubectl --request-timeout 5m get pod
